"""remove column in mechanic

Revision ID: 339900a9f0bc
Revises: 9936e86fc102
Create Date: 2025-01-29 18:41:06.278775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339900a9f0bc'
down_revision = '9936e86fc102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
