"""mileage culumn drop

Revision ID: 760079a30f90
Revises: dd2be92a8d56
Create Date: 2025-03-27 11:47:05.047615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760079a30f90'
down_revision = 'dd2be92a8d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('current_mileage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_mileage', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
