"""models vehicle

Revision ID: dd2be92a8d56
Revises: 8e3d8bf559c6
Create Date: 2025-03-24 09:46:15.065492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2be92a8d56'
down_revision = '8e3d8bf559c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_plate', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('current_mileage', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_service_date', sa.Date(), nullable=False))
        batch_op.create_unique_constraint('uq_vehicles_number_plate', ['number_plate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('last_service_date')
        batch_op.drop_column('current_mileage')
        batch_op.drop_column('number_plate')

    # ### end Alembic commands ###
